/**
 * @type {import('lint-staged').Config}
 */
module.exports = {
  // only run on your source files. generated code (*.gen.ts) and
  // d.ts artifacts are excluded — they're regenerated by wagmi/typechain
  // and shouldn't block commits on cosmetic warnings.
  '**/src/**/!(*.gen|*.d).{js,jsx,ts,tsx}': [
    'prettier --write --cache --cache-location .cache/.prettiercache',
    'eslint --fix --cache --cache-location .cache/.eslintcache',
  ],
  '**/src/**/*.{json,yaml,yml,md,mdx}': [
    'prettier --write --cache --cache-location .cache/.prettiercache',
  ],
};
